apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: demo-app
deploy:
  helm:
    releases:
    - name: demo-app
      chartPath: charts/demo-app
      wait: true
      setValues:
        imagePullPolicy: IfNotPresent
      values:
        image: demo-app
      setValueTemplates:
        ingress.domain: "{{if .INGRESS_DOMAIN}}{{.INGRESS_DOMAIN}}{{else}}local{{end}}"
        #istioDomain: "{{.ISTIO_DOMAIN}}"
        productName: "{{.PRODUCT_NAME}}"
      imageStrategy:
        helm: {}
profiles:
- name: local
  activation:
    - kubeContext: docker-for-desktop
    - kubeContext: docker-desktop
  build:
    artifacts:
    - image: demo-app
    local:
      useBuildkit: true
  portForward:
    - resourceType: deployment
      resourceName: demo-app
      port: 8081
      localPort: 8081
  deploy:
    helm:
      releases:
        - name: demo-app
          chartPath: charts/demo-app
          wait: true
          setValues:
            imagePullPolicy: IfNotPresent
          values:
            image: demo-app
          setValueTemplates:
            service.type: "NodePort"
          imageStrategy:
            helm: {}
